# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

m1	=	Mood.create!(name:	'Accepted', db_genre_id:	'10751,10402,10749', db_opp_genre_id:	'27,18')
m2	=	Mood.create!(name:	'Alone', db_genre_id:	'15,18,36', db_opp_genre_id:	'35,9')
m3	=	Mood.create!(name:	'Amused', db_genre_id:	'35,10749', db_opp_genre_id:	'9,910,752')
m4	=	Mood.create!(name:	'Angry', db_genre_id:	'99,80', db_opp_genre_id:	'35,28')
m5	=	Mood.create!(name:	'Anxious', db_genre_id:	'10770,27', db_opp_genre_id:	'10751')
m6	=	Mood.create!(name:	'Bewildered', db_genre_id:	'99,10769', db_opp_genre_id:	'10749,10751')
m7	=	Mood.create!(name:	'Bittersweet', db_genre_id:	'`18,10749', db_opp_genre_id:	'12,35')
m8	=	Mood.create!(name:	'Blah', db_genre_id:	'36,99', db_opp_genre_id:	'35,14')
m9	=	Mood.create!(name:	'Blissful', db_genre_id:	'35', db_opp_genre_id:	'18,10402')
m10	=	Mood.create!(name:	'Bored', db_genre_id:	'36', db_opp_genre_id:	'28')
m11	=	Mood.create!(name:	'Confused', db_genre_id:	'10769', db_opp_genre_id:	'10749')
m12	=	Mood.create!(name:	'Cranky', db_genre_id:	'9648', db_opp_genre_id:	'35')
m13	=	Mood.create!(name:	'Crazy', db_genre_id:	'28,12,878', db_opp_genre_id:	'10751')
m14	=	Mood.create!(name:	'Curious', db_genre_id:	'99', db_opp_genre_id:	'28')
m15	=	Mood.create!(name:	'Cynical', db_genre_id:	'99,18', db_opp_genre_id:	'10751,35,16')
m16	=	Mood.create!(name:	'Depressed', db_genre_id:	'99,18', db_opp_genre_id:	'35,16')
m17	=	Mood.create!(name:	'Ditzy', db_genre_id:	'10749,35', db_opp_genre_id:	'99,10769')
m18	=	Mood.create!(name:	'Dorky', db_genre_id:	'878,14', db_opp_genre_id:	'10749,35')
m19	=	Mood.create!(name:	'Drunk', db_genre_id:	'28', db_opp_genre_id:	'10769')
m20	=	Mood.create!(name:	'Ecstatic', db_genre_id:	'16,35', db_opp_genre_id:	'99')
m21	=	Mood.create!(name:	'Flirty', db_genre_id:	'10749', db_opp_genre_id:	'37')
m22	=	Mood.create!(name:	'Geeky', db_genre_id:	'16,28', db_opp_genre_id:	'10751,10402')
m23	=	Mood.create!(name:	'Giggly', db_genre_id:	'35', db_opp_genre_id:	'37')
m24	=	Mood.create!(name:	'Grateful', db_genre_id:	'10751', db_opp_genre_id:	'10769')
m25	=	Mood.create!(name:	'Grumpy', db_genre_id:	'99,10752', db_opp_genre_id:	'35')
m26	=	Mood.create!(name:	'Happy', db_genre_id:	'35', db_opp_genre_id:	'18,10770')
m27	=	Mood.create!(name:	'High', db_genre_id:	'16,14', db_opp_genre_id:	'10752')
m28	=	Mood.create!(name:	'Indifferent', db_genre_id:	'14', db_opp_genre_id:	'99')
m29	=	Mood.create!(name:	'Lazy', db_genre_id:	'35', db_opp_genre_id:	'99')
m30	=	Mood.create!(name:	'Lonely', db_genre_id:	'18,27', db_opp_genre_id:	'35,10751')
m31	=	Mood.create!(name:	'Loved', db_genre_id:	'10751', db_opp_genre_id:	'18,10770')
m32	=	Mood.create!(name:	'Mellow', db_genre_id:	'35', db_opp_genre_id:	'27')
m33	=	Mood.create!(name:	'Mischievous', db_genre_id:	'80,10770,9648', db_opp_genre_id:	'10751')
m34	=	Mood.create!(name:	'Nerdy', db_genre_id:	'14,878,12', db_opp_genre_id:	'10749')
m35	=	Mood.create!(name:	'Quixotic', db_genre_id:	'10769,12', db_opp_genre_id:	'10751')
m36	=	Mood.create!(name:	'Relaxed', db_genre_id:	'35', db_opp_genre_id:	'10770,27,9648')
m37	=	Mood.create!(name:	'Restless', db_genre_id:	'10751,18', db_opp_genre_id:	'12')
m38	=	Mood.create!(name:	'Sad', db_genre_id:	'18', db_opp_genre_id:	'35,10749')
m39	=	Mood.create!(name:	'Silly', db_genre_id:	'35', db_opp_genre_id:	'18')
m40	=	Mood.create!(name:	'Smart', db_genre_id:	'99,10769', db_opp_genre_id:	'10749,35,10751')
m41	=	Mood.create!(name:	'Stressed', db_genre_id:	'10770,9648', db_opp_genre_id:	'16,35')
m42	=	Mood.create!(name:	'Weird', db_genre_id:	'16,878', db_opp_genre_id:	'10402,10749')

mov1 = Movie.create!(name: 'Christine', image: '', mood_id: m12.id, director: 'john', actors: 'billy, clarence', plot: 'killer clown', genre: 'Horror')
mov2 = Movie.create!(name: 'Drive', image: '', mood_id: m17.id, director: 'sarah', actors: 'Ryan Duckling', plot: 'a chauffeur drives around LA', genre: 'Thriller')
mov3 = Movie.create!(name: 'Step Brothers', image: '', mood_id: m4.id, director: 'Cramperton', actors: 'Bill Terrell', plot: 'brothers are silly', genre: 'Comedy')
mov4 = Movie.create!(name: 'Bowling for Columnbine', image: '', mood_id: m6.id, director: 'Fatty Fatterson', actors: '', plot: 'the world\'s best bowlers', genre: 'Documentary')
mov5 = Movie.create!(name: 'The Maltese Falcon', image: '', mood_id: m14.id, director: 'some odl dude', actors: 'Humpty Bogardt', plot: 'a bird from malta gets up to some hijinks!', genre: 'Mystery')
mov6 = Movie.create!(name: 'Lord of the Things', image: '', mood_id: m9.id, director: 'Peateaer Craksonn', actors: 'Short dudes', plot: 'A guy llikes things so becomes lord of them', genre: 'Fantasy')

c1 = Comment.create(comment: 'He drives so good', movie_id: mov2.id)
c2 = Comment.create(comment: 'old timey film', movie_id: mov5.id)
c3 = Comment.create(comment: 'short and tall peeple will like this', movie_id: mov6.id)

puts 'seeded'
